### ISSUE TITLE
Proposing Project Logo

### ISSUE THREAD

**Issue by localleon** [pborges/gbridge#18]
Would be nice to have a logo for this project.

**Comment by localleon** [comment]
It could be as simple as something like this. But i will try some other designs to.,

![gBridge_Logo](https://user-images.githubusercontent.com/28186014/70862215-c3fdab80-1f39-11ea-8610-2da166a1844e.png)

**Comment by pborges** [comment]
This idea might work for now, but could we use the gopher megaphone hes my favorite XD 
![gopher_megaphone_sticker_true_color_square](https://user-images.githubusercontent.com/2800445/70865124-9fd8a500-1f0e-11ea-9a63-1eb7d8ffdc8d.png)

**Comment by localleon** [comment]
![gBridge_Logo](https://user-images.githubusercontent.com/28186014/70865576-798f2580-1f5f-11ea-9c35-9ab2fecfd914.png)

**Comment by pborges** [comment]
Will defiantly use this if only for a placeholder, but as most things go it will most likely become permanent XD

**Comment by localleon** [comment]
Banner Upload:

![gBridge_banner](https://user-images.githubusercontent.com/28186014/71015708-5d70bd00-20f4-11ea-88a8-976b19ccbd7f.png)
